ERM/ERM/urls.py
from django.contrib import admin
from django.urls import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ERMapp.urls')),
]

ERM/ERMapp/urls.py
from django.urls import path
from . import views

app_name = 'data'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.homefunc, name='homefunc'),
    path('order/', views.formvalue, name='formvalue'),
]

ERM/ERMapp/models.py
from django.db import models

# Create your models here.


class Customer(models.Model):
    customerCode = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    orderNumber = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.customerCode} - {self.name} - {self.orderNumber}"


class Item(models.Model):
    itemCode = models.AutoField(primary_key=True)
    itemName = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    unitPrice = models.FloatField(max_length=255)
    stock = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.itemCode} - {self.itemName} - {self.description} - {self.unitPrice} - {self.stock}"


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    customerCode = models.CharField(max_length=255, null=True)
    customerName = models.CharField(max_length=255, null=True)
    customerOrderNumber = models.CharField(max_length=255, null=True)
    customerOrderDate = models.CharField(max_length=255, null=True)
    itemCode = models.IntegerField(null=True)
    itemName = models.CharField(max_length=255)
    quantity = models.IntegerField(null=True)
    unitPrice = models.FloatField(max_length=255)
    stock = models.IntegerField(null=True)
    total = models.FloatField(max_length=255)

    def __str__(self):
        return f"{self.id} - {self.customerCode} - {self.customerName} - {self.customerOrderNumber} - {self.customerOrderDate} - {self.itemCode} - {self.itemName} - {self.quantity} - {self.unitPrice} - {self.stock} - {self.total}"

ERM/ERMapp/views.py
from django.shortcuts import *
from django.http import *
from .models import *

# Create your views here.


def home(request): # Home Display
    return render(request, 'ERMapp/demo.html')


def homefunc(request): # For Customer Order
    code = request.POST.get('code')
    itemCode = request.POST.getlist('itemCode[]')
    print(f"Received code: {code}, itemCode: {itemCode}")
    customers = Customer.objects.all()
    items = Item.objects.all()
    if code:
        for x in customers:
            if x.customerCode == int(code):
                context = {'values': Customer.objects.filter(customerCode=code).values()}
                return render(request, 'ERMapp/demo.html', context)
    else:
        return HttpResponse("Empty")
    return HttpResponse("Doesn't Exist")


def formvalue(request): # For Items
    if request.method == 'POST':
        date_arr = []
        customerCode = request.POST.get('customerCode')
        customerName = request.POST.get('customerName')
        customerOrderNumber = request.POST.get('customerOrderNumber')
        customerOrderDate = request.POST.get('customerOrderDate')
        itemCode = request.POST.getlist('itemCode[]')
        itemName = request.POST.getlist('itemName[]')
        quantity = request.POST.getlist('quantity[]')
        stock = request.POST.getlist('stock[]')
        unitPrice = request.POST.getlist('unitPrice[]')
        total = request.POST.getlist('total[]')

        # For Input Data From Item
        if all(field and any(value.strip() for value in field) for field in
               [customerCode, customerName, customerOrderNumber, customerOrderDate, itemCode, itemName, quantity, stock, unitPrice, total]):
            # Order entry
            for x in range(len(itemCode)):
                account = Order(customerCode=customerCode, customerName=customerName, customerOrderNumber=customerOrderNumber, customerOrderDate=customerOrderDate, itemCode=itemCode[x], itemName=itemName[x], quantity=quantity[x], unitPrice=unitPrice[x], stock=stock[x], total=total[x])
                account.save()
            return HttpResponse("Registration Successful!")
        elif itemCode != 0 or itemCode != "":
            items = Item.objects.all()
            for x in itemCode:
                for y in items:
                    if int(x) and int(x) == y.itemCode:
                        date_arr.extend(Item.objects.filter(itemCode=int(x)))
            context = {'itemValues': date_arr}
            return render(request, 'ERMapp/demo.html', context)
        else:
            return HttpResponse("Something went Wrong !")
    else:
        return HttpResponse("Invalid request method.")


# def formvalue(request):
#     if request.method == 'POST':
#         date_arr = []
#         itemCode = request.POST.getlist('itemCode[]')
#         itemName = request.POST.getlist('itemName[]')
#         quantity = request.POST.getlist('quantity[]')
#         stock = request.POST.getlist('stock[]')
#         unitPrice = request.POST.getlist('unitPrice[]')
#         total = request.POST.getlist('total[]')
#
#         # Check if any required fields are empty
#         if not (itemCode and itemName and quantity and stock and unitPrice and total):
#             items = Item.objects.all()
#             for x in itemCode:
#                 for y in items:
#                     if x.isdigit() and int(x) == y.itemCode:  # Ensure itemCode is numeric
#                         date_arr.extend(Item.objects.filter(itemCode=int(x)).values())
#             context = {'itemValues': date_arr}
#             return render(request, 'ERMapp/demo.html', context)
#
#         elif itemCode != 0 and itemName != 0 and quantity and stock and unitPrice and total:
#             # Order entry
#             for x in range(len(itemCode)):
#                 try:
#                     account = Order(
#                         itemCode=itemCode[x],
#                         itemName=itemName[x],
#                         quantity=int(quantity[x]) if quantity[x].strip() else 0,  # Convert empty string to 0
#                         unitPrice=float(unitPrice[x]) if unitPrice[x].strip() else 0.0,  # Convert to float
#                         stock=int(stock[x]) if stock[x].strip() else 0,  # Convert to int
#                         total=float(total[x]) if total[x].strip() else 0.0  # Convert to float
#                     )
#                     account.save()
#                 except ValueError:
#                     return HttpResponse("Invalid number format in form fields.")
#
#             return HttpResponse("Registration Successful!")
#
#         else:
#             return HttpResponse("Something went wrong!")
#
#     else:
#         return HttpResponse("Invalid request method.")

ERM/ERMapp/templates/ERMapp/index.html
<!-- =========== First Html File. Half Work =============== -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Sample</title>
    <meta charset="utf-8" />
    <!-- For Bootstrap 5 -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- For JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/b5c2cc2edf.js" crossorigin="anonymous"></script>
    <!-- For CSS -->
    {% load static %}
    <link href="{% static 'ERMapp/mouse.css' %}" rel="stylesheet" />
  </head>
  <body>
    <script>
      var cardNo = 1 // Declared globally
      var temp = 0
    </script>
    <form id="myForm" method="post" action="{% url 'data:homefunc' %}">
      {% csrf_token %}
      <div class="container-fluid pt-3">
        <!-- ===== Sales Order ===== -->
        <div class="card rounded">
          <div class="card-body">
            <div class="col-12 d-flex justify-content-center bg-success shadow">
              <h1 class="p-3 text-white">Sales Order</h1>
            </div>
            <div class="row pt-3">
              <div class="col-xl-2">
                <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Customer Code:</label>
              </div>
              <div class="col-xl-4">
                <div data-mdb-input-init class="form-outline pb-4 pe-4">
                  <input type="number" class="form-control" placeholder="Customer Code" name="code" id="code" onchange="insert()" />
                  <span></span>
                  <script>
                    function insert() {
                      const applicantForm = document.querySelector('form')
                      applicantForm.addEventListener('keypress', function (event) {
                        if (event.keyCode === 13) {
                          event.preventDefault()
                          applicantForm.submit()
                        }
                      })
                    }
                  </script>
                </div>
              </div>
              <div class="col-xl-2">
                <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Customer Name:</label>
              </div>
              <div class="col-xl-4">
                <div data-mdb-input-init class="form-outline pb-4 pe-4">
                  <input type="text" class="form-control" placeholder="Customer Name" name="name" id="name" value="" />
                  <span></span>
                </div>
              </div>
            </div>
            <div class="row pt-3">
              <div class="col-xl-2">
                <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Order Number:</label>
              </div>
              <div class="col-xl-4">
                <div data-mdb-input-init class="form-outline pb-4 pe-4">
                  <input type="text" class="form-control" placeholder="Order Number" name="orderNumber" id="orderNumber" value="" />
                  <span></span>
                </div>
              </div>
              <div class="col-xl-2">
                <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Order Date:</label>
              </div>
              <div class="col-xl-4">
                <div data-mdb-input-init class="form-outline pb-4 pe-4">
                  <input type="date" class="form-control" name="date" id="date" />
                  <span></span>
                  <script>
                    let currentDate = new Date()
                    let formattedDate = currentDate.toISOString().split('T')[0]
                    document.getElementById('date').value = formattedDate
                  </script>
                </div>
              </div>

              {% for x in values %}
                <script>
                  let customerCode = '{{ x.customerCode }}'
                  let name = '{{ x.name }}'
                  let orderNumber = '{{ x.orderNumber }}'
                  document.getElementById('code').value = customerCode
                  document.getElementById('name').value = name
                  document.getElementById('orderNumber').value = orderNumber
                </script>
              {% endfor %}
            </div>
          </div>
        </div>

        <hr />
        <h2 class="text-center">Items</h2>
        <hr />
        <!-- ===== Items ===== -->

        <div id="container"></div>
        <script>
          let container = document.getElementById('container')
          function card() {
            let cardHTML = `
                          <div class="pt-3">
                            <div class="card rounded shadow bg-light">
                              <div class="card-body">
                                <div class="row pt-3">
                                  <div class="col-lg-2">
                                    <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Item Code:</label>
                                  </div>
                                  <div class="col-lg-2">
                                    <div data-mdb-input-init class="form-outline pb-4 pe-4">
                                      <input type="number" class="form-control" placeholder="Item Code" name="itemCode[]" onchange="insert()" />
                                      <span></span>
                                    </div>
                                  </div>
                                  <div class="col-lg-2">
                                    <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Item Name:</label>
                                  </div>
                                  <div class="col-lg-2">
                                    <div data-mdb-input-init class="form-outline pb-4 pe-4">
                                      <input type="text" class="form-control" placeholder="Item Name" name="itemName" id="itemName" />
                                      <span></span>
                                    </div>
                                  </div>
                                  <div class="col-lg-2">
                                    <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Quantity:</label>
                                  </div>
                                  <div class="col-lg-2">
                                    <div data-mdb-input-init class="form-outline pb-4 pe-4">
                                      <input type="number" class="form-control" placeholder="Quantity" name="quantity" id="quantity" />
                                      <span></span>
                                    </div>
                                  </div>
                                </div>
          
                                <div class="row pt-3">
                                  <div class="col-lg-2">
                                    <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Stock:</label>
                                  </div>
                                  <div class="col-lg-2">
                                    <div data-mdb-input-init class="form-outline pb-4 pe-4">
                                      <input type="number" class="form-control" placeholder="Stock" name="stock" id="stock" />
                                      <span></span>
                                    </div>
                                  </div>
                                  <div class="col-lg-2">
                                    <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Unit Price:</label>
                                  </div>
                                  <div class="col-lg-2">
                                    <div data-mdb-input-init class="form-outline pb-4 pe-4">
                                      <input type="number" class="form-control" placeholder="Unit Price" name="unitPrice" id="unitPrice" />
                                      <span></span>
                                    </div>
                                  </div>
                                  <div class="col-lg-2">
                                    <label class="lead" style="font-family: Times New Roman, Times, serif;"><i class="fa-solid fa-user ps-3 pe-3"></i>Total:</label>
                                  </div>
                                  <div class="col-lg-2">
                                    <div data-mdb-input-init class="form-outline pb-4 pe-4">
                                      <input type="number" class="form-control" placeholder="Total" name="total" id="total" />
                                      <span></span>
                                    </div>
                                  </div>
          
                                </div>
                              </div>
                            </div>
                          </div>
          
                            `
            container.innerHTML += cardHTML
          }
          card()
        </script>

        {% for x in item %}
          <script>
            let itemCode = '{{ x.itemCode }}'
            let itemName = '{{ x.itemName }}'
            let unitPrice = '{{ x.unitPrice }}'
            let stock = '{{ x.stock }}'
            
            let inputFields = document.getElementsByName('itemCode[]')
            
            // Find the first empty input field and set the value
            for (let i = 0; i < inputFields.length; i++) {
              if (inputFields[i].value === '') {
                inputFields[i].value = itemCode
                break // Assign once per loop iteration
              }
            }
            document.getElementById('itemName').value = itemName
            document.getElementById('unitPrice').value = unitPrice
            document.getElementById('stock').value = stock
          </script>
        {% endfor %}

        <div class="pt-3 d-flex justify-content-end">
          <button type="submit" class="btn btn-success btn-lg">Save</button>
        </div>
      </div>
    </form>

    <div class="menu">
      <div class="menu-list">
        <div class="section">
          <div class="item" onclick="incrementCounter()">
            <div class="name">ADD</div>
          </div>
          <script>
            function incrementCounter() {
              card()
            }
          </script>
          <div class="item">
            <div class="name">Delete</div>
          </div>
        </div>
      </div>
    </div>
    <script>
      let menu = document.querySelector('.menu')
      let intiHeight = menu.offsetHeight
      let initWidth = menu.offsetWidth
      menu.style.display = 'none'
      window.addEventListener('contextmenu', (e) => {
        e.preventDefault()
      
        let positionX = e.clientX
        let positionY = e.clientY
        let wHeight = window.innerHeight
        let wWidth = window.innerWidth
      
        let menuHeight = menu.offsetHeight || intiHeight
        let menuWidth = menu.offsetWidth || initWidth
      
        let availableHeight = wHeight - positionY
        let availableWidth = wWidth - positionX
      
        if (availableHeight >= menuHeight) {
          menu.style.top = positionY + 'px'
          menu.style.bottom = 'auto'
        } else {
          menu.style.bottom = wHeight - positionY + 'px'
          menu.style.top = 'auto'
          if (positionY < menuHeight) {
            menu.style.top = '0px'
            menu.style.bottom = 'auto'
          }
        }
      
        if (availableWidth >= menuWidth) {
          menu.style.left = positionX + 'px'
          menu.style.right = 'auto'
        } else {
          menu.style.right = wWidth - positionX + 'px'
          menu.style.left = 'auto'
        }
        menu.style.display = 'block'
      })
      
      window.addEventListener('click', () => {
        menu.style.display = 'none'
      })
    </script>
  </body>
</html>